list_category:
  path: /
  controller: Alexandrie\Controller\CategoryController::listCategoryAction
  methods: GET

list_category_id:
  path: /{id}
  controller: Alexandrie\Controller\CategoryController::listCategoryByIdAction
  methods: GET

delete_category_id:
  path: /{id}
  controller: Alexandrie\Controller\CategoryController::deleteCategoryByIdAction
  methods: DELETE

add_category_id:
  path: /{id}
  controller: Alexandrie\Controller\CategoryController::addCategory
  methods: PUT

patch_category_id:
  path: /{id}
  controller: Alexandrie\Controller\CategoryController::updateCategory
  methods: PATCH