category_list:
  path: /
  controller: Alexandrie\Controller\CategoryController::list
  methods: ['POST','GET']
category_create:
  path: /
  methods: ['PUT']
  controller: Alexandrie\Controller\CategoryController::create
category_get:
  path: /{id}
  requirements:
    id: '\d+'
  methods: ['GET']
  controller: Alexandrie\Controller\CategoryController::getCategory
category_edit:
  path: /{id}
  requirements:
    id: '\d+'
  methods: ['PATCH']
  controller: Alexandrie\Controller\CategoryController::edit
category_delete:
  path: /{id}
  requirements:
    id: '\d+'
  methods: ['DELETE']
  controller: Alexandrie\Controller\CategoryController::delete