category-list:
  path: /
  methods: ['GET']
  controller: Alexandrie\Controller\CategoryController::list

category-create:
  path: /
  methods: ['PUT']
  controller: Alexandrie\Controller\CategoryController::create

category-retrieve:
  path: /{id}
  requirements:
    id: \d+
  methods: ['GET']
  controller: Alexandrie\Controller\CategoryController::retrieve

category-update:
  path: /{id}
  requirements:
    id: \d+
  methods: ['PATCH']
  controller: Alexandrie\Controller\CategoryController::update

category-delete:
  path: /{id}
  requirements:
    id: \d+
  methods: ['DELETE']
  controller: Alexandrie\Controller\CategoryController::delete