list:
  path: /
  controller: Alexandrie\Controller\CopyController::list
  methods: GET

add:
  path: /
  controller: Alexandrie\Controller\CopyController::add
  methods: PUT

find:
  path: /{id}
  controller: Alexandrie\Controller\CopyController::find
  methods: GET
  requirements:
    id: '\d+'

update:
  path: /{id}
  controller: Alexandrie\Controller\CopyController::update
  methods: PATCH
  requirements:
    id: '\d+'

delete:
  path: /{id}
  controller: Alexandrie\Controller\CopyController::delete
  methods: DELETE
  requirements:
    id: '\d+'