copy_list:
  path: /
  controller: Alexandrie\Controller\CopyController::list
  methods: ['POST','GET']
copy_create:
  path: /
  methods: ['PUT']
  controller: Alexandrie\Controller\CopyController::create
copy_get:
  path: /{id}
  requirements:
    id: '\d+'
  methods: ['GET']
  controller: Alexandrie\Controller\CopyController::getCopy
copy_edit:
  path: /{id}
  requirements:
    id: '\d+'
  methods: ['PATCH']
  controller: Alexandrie\Controller\CopyController::edit
copy_delete:
  path: /{id}
  requirements:
    id: '\d+'
  methods: ['DELETE']
  controller: Alexandrie\Controller\CopyController::delete