ListCopy:
  path: /
  controller: Alexandrie\Controller\CopyController::list
  methods: [GET]

DetailCopy:
  path: /{id}
  controller: Alexandrie\Controller\CopyController::detail
  methods: [GET]
  requirements:
    id: \d+

DeleteCopy:
  path: /{id}
  controller: Alexandrie\Controller\CopyController::delete
  methods: [DELETE]
  requirements:
    id: \d+