ListLending:
  path: /
  controller: Alexandrie\Controller\LendingController::list
  methods: [GET]

DetailLending:
  path: /{id}
  controller: Alexandrie\Controller\LendingController::detail
  methods: [GET]
  requirements:
    id: \d+

DeleteLending:
  path: /{id}
  controller: Alexandrie\Controller\LendingController::delete
  methods: [DELETE]
  requirements:
    id: \d+