listLending:
  path: /
  controller: Alexandrie\Controller\LendingController::lendingList
  methods: ['GET']

lending:
  path: /{id}
  controller: Alexandrie\Controller\LendingController::getLending
  requirements:
    id: '\d+'
  methods: ['GET']

createLending:
  path: /
  controller: Alexandrie\Controller\LendingController::createLending
  methods: ['PUT']

updateLending:
  path: /{id}
  controller: Alexandrie\Controller\LendingController::updateLending
  requirements:
    id: '\d+'
  methods: ['PATCH']

deleteLending:
  path: /{id}
  controller: Alexandrie\Controller\LendingController::deleteLending
  requirements:
    id: '\d+'
  methods: ['DELETE']

