library-display-all:
  path: /
  controller: Alexandrie\Controller\BookController::displayAll
  methods: GET

library-add:
  path: /
  controller: Alexandrie\Controller\BookController::add
  methods: PUT

library-display:
  path: /{id}
  controller: Alexandrie\Controller\BookController::display
  methods: GET
  requirements:
    id: \d+

library-update:
  path: /{id}
  controller: Alexandrie\Controller\BookController::update
  methods: PATCH
  requirements:
    id: \d+

library-delete:
  path: /{id}
  controller: Alexandrie\Controller\BookController::delete
  methods: DELETE
  requirements:
    id: \d+