list:
  path: /
  controller: Alexandrie\Controller\ReaderController::list
  methods: GET

add:
  path: /
  controller: Alexandrie\Controller\ReaderController::add
  methods: PUT

find:
  path: /{id}
  controller: Alexandrie\Controller\ReaderController::find
  methods: GET
  requirements:
    id: '\d+'

update:
  path: /{id}
  controller: Alexandrie\Controller\ReaderController::update
  methods: PATCH
  requirements:
    id: '\d+'

delete:
  path: /{id}
  controller: Alexandrie\Controller\ReaderController::delete
  methods: DELETE
  requirements:
    id: '\d+'