reader_list:
  path: /
  controller: Alexandrie\Controller\ReaderController::list
  methods: ['POST','GET']
reader_create:
  path: /
  methods: ['PUT']
  controller: Alexandrie\Controller\ReaderController::create
reader_get:
  path: /{id}
  requirements:
    id: '\d+'
  methods: ['GET']
  controller: Alexandrie\Controller\ReaderController::getReader
reader_edit:
  path: /{id}
  requirements:
    id: '\d+'
  methods: ['PATCH']
  controller: Alexandrie\Controller\ReaderController::edit
reader_delete:
  path: /{id}
  requirements:
    id: '\d+'
  methods: ['DELETE']
  controller: Alexandrie\Controller\ReaderController::delete