listReader:
  path: /
  controller: Alexandrie\Controller\ReaderController::readerList
  methods: ['GET']

reader:
  path: /{id}
  controller: Alexandrie\Controller\ReaderController::getReader
  requirements:
    id: '\d+'
  methods: ['GET']

createReader:
  path: /
  controller: Alexandrie\Controller\ReaderController::createReader
  methods: ['PUT']

updateReader:
  path: /{id}
  controller: Alexandrie\Controller\ReaderController::updateReader
  requirements:
    id: '\d+'
  methods: ['PATCH']

deleteReader:
  path: /{id}
  controller: Alexandrie\Controller\ReaderController::deleteReader
  requirements:
    id: '\d+'
  methods: ['DELETE']

