# config/packages/dev/maker.yaml
# create this file if you need to configure anything
maker:
  # tell MakerBundle that all of my classes lives in an
  # Alexandrie namespace, instead of the default App
  root_namespace: 'Alexandrie'