#index:
#    path: /
#    controller: Alexandrie\Controller\DefaultController::index

# Category Related
category:
  resource: './routes/category.yaml'
  prefix: /category

# Book Related
book:
  resource: './routes/book.yaml'
  prefix: /book

# Reader Related
reader:
  resource: './routes/reader.yaml'
  prefix: /reader

# Library Related
library:
  resource: './routes/library.yaml'
  prefix: /library

# LendingRepository Related
lending:
  resource: './routes/lending.yaml'
  prefix: /lending

# Copy Related
copy:
  resource: './routes/copy.yaml'
  prefix: /copy

